title: Containerization & DevOps
description: Learning journey and hands-on experiments

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: dark
enable_theme_switcher: true

search_enabled: true
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Built by Dhairya Thareja ðŸš€"

aux_links:
  "View on GitHub":
    - "https://github.com/dhairyathareja/DhairyaThareja_Containerization-DevOps"